name: File Operations Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:

jobs:
  push_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Push a File
        run: |
          echo "numpy" > requirements.txt
          git config --global user.name "Mantra-Jain"
          git config --global user.email "mj.mantrajain@gmail.com"
          git add requirements.txt
          git commit -m "Add requirements.txt"
          git push origin main
  pull_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull a File
        run: |
          git fetch origin main
          git checkout main
          git pull origin main
          cat calculator.py  
  manual_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Manual Dispatch
        run: echo "This job was manually triggered"
